### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by wilsonnkwan** [randyzhong/OS-X-NUC8i7BEH-Clover#2]
Hi, total noob here btw, so if my question sound idiotic, I apologise.

I don't have a Mac to start with so, I installed the MacOS using Daliansky's 5033 image. 
Then to insert your EFI, I used daliansky's 5050 image which when etched, there is a partition for me to modify the EFI. So i inserted your EFI instead of theirs.

My system is NUC8i7BEH with 0071 BIOS. I have set the settings per your recommendation. while the apple logo is loading, it turns green and then it get either stuck or the system restarts itself.

Want to ask, which image you used and is there any instruction for making images and clover using windows.

Help. Thanks

**Comment by wilsonnkwan** [comment]
Okey, A abit of update, it loads into the middle, I can move my mouse but in the middle it restarts. Any ideas?

**Comment by randyzhong** [comment]
Hi wilsonnkwan, I am using official Mac App Store (MAS) macOS image, I don't have experience on installing with Daliansky's image. Please try to use MAS image and see if any difference.

**Comment by randyzhong** [comment]
Close this issue as no further information/feedback received.
