### ISSUE TITLE
Anyone has the EFI config files for Catalina?

### ISSUE THREAD

**Issue by wilsonnkwan** [randyzhong/OS-X-NUC8i7BEH-Clover#3]
The whole problem with me at least is, I know how to install but I don't know how to configure what part i need in the EFI, what kext, what drivers... sorry bros, total noobs, need help

**Comment by randyzhong** [comment]
Get a USB stick, formatted as FAT32, copy the whole EFI folder/files to the thumb drive will be a easy way to boot from Clover. You will need to make another drive for macOS installer. If you can boot to macOS, modify clover config file to customize your hackintosh model/SN/Board... etc. info.

Note: These clover files are applicable for Catalina.

**Comment by randyzhong** [comment]
These Clover EFI files are working for Catalina, hence close this issue.
