### ISSUE TITLE
BCM94360CS2/PCI-E Mod PCB

### ISSUE THREAD

**Issue by sffjawsh** [randyzhong/OS-X-NUC8i7BEH-Clover#6]
@randyzhong Great work on getting this to work on the NUC8i7BEH. Finally the missing piece to make this a great hackintosh. Is the Mod PCB/Instructions to desolder/replace available for sale?

**Comment by randyzhong** [comment]
@sffjawsh Yes, the Mod PCB designer is selling the mod kit in Chinese website. I can help you to get it if you like, just drop me an email.

**Comment by randyzhong** [comment]
@sffjawsh Would you please check your inbox? I replied some messages to your request but no response yet. Could be filtered to your email Spam folder?
